import { useEffect, useRef, Fragment } from 'react'
import { useLocation } from 'react-router-dom'
import Nav from '../../components/Nav/Nav'
import Footer from '../../components/Footer/Footer'
import styles from './Confirmation.module.css'

// ── Helpers ───────────────────────────────────────────────────────────────────

function triggerPDFDownload(disc, recv) {
  const text = `NON-DISCLOSURE AGREEMENT\n\nThis agreement is entered into between ${disc || '[Disclosing party name]'} and ${recv || '[Receiving party name]'}.\n\nThis document was generated by LegalShield. For prototype purposes only.`
  const blob = new Blob([text], { type: 'application/pdf' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = 'NDA_JaneSmith_AcmeCorp.pdf'
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

// ── Icons ─────────────────────────────────────────────────────────────────────

function CheckCircleIcon() {
  return (
    <svg className={styles.successIcon} viewBox="0 0 24 24" fill="none">
      <circle cx="12" cy="12" r="12" fill="#1a7a3f" />
      <polyline points="6,12 10,16 18,8" stroke="#fff" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

function StepCheckIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
      <polyline points="2,6.5 5,9.5 10,3" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

function DownloadIcon() {
  return (
    <svg className={styles.rowIcon} viewBox="0 0 20 20" fill="none">
      <path d="M10 3v10M6 9l4 4 4-4" stroke="#555" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" />
      <path d="M3 15h14" stroke="#555" strokeWidth="1.6" strokeLinecap="round" />
    </svg>
  )
}

function EmailIcon() {
  return (
    <svg className={styles.rowIcon} viewBox="0 0 20 20" fill="none">
      <rect x="2" y="4" width="16" height="12" rx="2" stroke="#555" strokeWidth="1.6" />
      <path d="M2 7l8 5 8-5" stroke="#555" strokeWidth="1.6" strokeLinecap="round" />
    </svg>
  )
}

function ShieldBulletIcon() {
  return (
    <svg className={styles.bulletShield} viewBox="0 0 16 20" fill="none">
      <path d="M8 0L16 3.5v7C16 15 12.5 18.5 8 20 3.5 18.5 0 15 0 10.5v-7L8 0z" fill="#692BEE" />
    </svg>
  )
}

function DocDownloadIcon() {
  return (
    <svg width="13" height="13" viewBox="0 0 20 20" fill="none" style={{ verticalAlign: 'middle', marginLeft: 4 }}>
      <path d="M10 3v10M6 9l4 4 4-4" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
      <path d="M3 15h14" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
    </svg>
  )
}

// ── Filled value helper ───────────────────────────────────────────────────────

function Val({ value, placeholder }) {
  return value
    ? <span className={styles.docFilled}>{value}</span>
    : <span className={styles.docPlaceholder}>{placeholder}</span>
}

// ── Stepper (all steps complete) ──────────────────────────────────────────────

const STEP_LABELS = ['Parties', 'Confidential info', 'Obligations', 'Review']

function Stepper() {
  return (
    <div className={styles.stepper}>
      {STEP_LABELS.map((label, i) => (
        <Fragment key={label}>
          {i > 0 && <div className={`${styles.stepLine} ${styles.stepLineFilled}`} />}
          <div className={styles.stepItem}>
            <div className={`${styles.stepCircle} ${styles.stepCircleDark}`}>
              <StepCheckIcon />
            </div>
            <span className={`${styles.stepLabel} ${styles.stepLabelDone}`}>{label}</span>
          </div>
        </Fragment>
      ))}
    </div>
  )
}

// ── Right-column document preview (completed text, no watermark) ─────────────

function DocPreview({ form, onDownload }) {
  const disc = form.disclosingParty
  const recv = form.receivingParty

  const dateDisplay = (() => {
    if (!form.startDate) return null
    const [y, m, d] = form.startDate.split('-').map(Number)
    return new Date(y, m - 1, d).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })
  })()

  const title = (disc || recv)
    ? `Non-disclosure agreement — ${disc || '[Party 1]'} & ${recv || '[Party 2]'}.pdf`
    : 'Non-disclosure agreement.pdf'

  return (
    <div className={styles.docPreviewWrap}>
      <div className={styles.docPanel}>
        <div className={styles.docPanelHeader}>
          <span className={styles.docPanelTitle}>{title}</span>
          <button className={styles.docDownloadBtn} onClick={onDownload}>
            Download <DocDownloadIcon />
          </button>
        </div>
        <div className={styles.docText}>
          <p className={styles.docTextTitle}>Non-Disclosure Agreement</p>
          <hr className={styles.docTextDivider} />

          <p className={styles.docTextParagraph}>
            This Non-Disclosure Agreement (the &ldquo;Agreement&rdquo;) is entered into as of{' '}
            {dateDisplay
              ? <span className={styles.docFilled}>{dateDisplay}</span>
              : <span className={styles.docPlaceholder}>[Date]</span>
            }, by and between:
          </p>

          <p className={styles.docTextParagraph}>
            <Val value={disc} placeholder="[Disclosing Party Name]" />{' '}
            (the &ldquo;Disclosing Party&rdquo;), and{' '}
            <Val value={recv} placeholder="[Receiving Party Name]" />{' '}
            (the &ldquo;Receiving Party&rdquo;). Each party is sometimes referred to herein individually as a &ldquo;Party&rdquo; and collectively as the &ldquo;Parties.&rdquo;
          </p>

          <p className={styles.docTextSectionHead}>Recitals</p>
          <p className={styles.docTextParagraph}>
            WHEREAS, the Disclosing Party possesses certain confidential and proprietary information relating to its business operations, products, services, customers, and strategies; and
          </p>
          <p className={styles.docTextParagraph}>
            WHEREAS, the Receiving Party desires to receive certain of said confidential information for the purpose of evaluating a potential business relationship between the Parties;
          </p>
          <p className={styles.docTextParagraph}>
            NOW, THEREFORE, in consideration of the mutual covenants and agreements contained herein, the Parties agree as follows:
          </p>

          <p className={styles.docTextSectionHead}>1. Confidential Information</p>
          <p className={styles.docTextParagraph}>
            &ldquo;Confidential Information&rdquo; means any and all non-public information disclosed by the Disclosing Party to the Receiving Party, whether disclosed orally, in writing, or by any other means, that is designated as confidential or that reasonably should be understood to be confidential given the nature of the information and the circumstances of disclosure.
          </p>

          <p className={styles.docTextSectionHead}>2. Obligations of Receiving Party</p>
          <p className={styles.docTextParagraph}>
            The Receiving Party agrees to: (a) hold the Confidential Information in strict confidence; (b) not disclose the Confidential Information to any third party without the prior written consent of the Disclosing Party; (c) use the Confidential Information solely for the purposes described in this Agreement; and (d) protect the Confidential Information using the same degree of care it uses to protect its own confidential information, but in no event less than reasonable care.
          </p>

          <p className={styles.docTextSectionHead}>3. Term</p>
          <p className={styles.docTextParagraph}>
            The obligations of confidentiality set forth in this Agreement shall commence on the date first written above and shall continue for a period of{' '}
            {form.duration
              ? <span className={styles.docFilled}>{form.duration.toLowerCase()}</span>
              : <span className={styles.docPlaceholder}>[Duration]</span>
            }{' '}
            thereafter, unless earlier terminated by written agreement of the Parties.
          </p>

          <p className={styles.docTextSectionHead}>4. Governing Law</p>
          <p className={styles.docTextParagraph}>
            This Agreement shall be governed by and construed in accordance with the laws of the State of{' '}
            {form.governingState
              ? <span className={styles.docFilled}>{form.governingState}</span>
              : <span className={styles.docPlaceholder}>[State]</span>
            }, without regard to its conflict of law provisions.
          </p>

          <hr className={styles.docTextDivider} />
          <p className={styles.docTextSectionHead}>Signatures</p>
          <div className={styles.docTextSigBlock}>
            <div className={styles.docTextSigCol}>
              <div className={styles.docTextSigLine}>
                <Val value={disc} placeholder="[Disclosing Party]" />
              </div>
              <div className={styles.docTextSigLine}>Signature</div>
              <div className={styles.docTextSigLine}>Date</div>
            </div>
            <div className={styles.docTextSigCol}>
              <div className={styles.docTextSigLine}>
                <Val value={recv} placeholder="[Receiving Party]" />
              </div>
              <div className={styles.docTextSigLine}>Signature</div>
              <div className={styles.docTextSigLine}>Date</div>
            </div>
          </div>

          {/* No watermark — document is complete */}
        </div>
      </div>
      <p className={styles.docPageLabel}>Preview: page 1 of 4</p>
    </div>
  )
}

// ── Main ──────────────────────────────────────────────────────────────────────

const EMPTY_FORM = { disclosingParty: '', receivingParty: '', startDate: '', duration: '', governingState: '', email: '', infoTypes: [], description: '', relationship: '', allowedUse: '', sharing: '' }

export default function Confirmation() {
  const location = useLocation()
  const form = location.state?.form || EMPTY_FORM
  const { disclosingParty = '', receivingParty = '', email = '' } = form
  const pricingRef = useRef(null)

  useEffect(() => {
    triggerPDFDownload(disclosingParty, receivingParty)
  }, [])

  function handleDownload() {
    triggerPDFDownload(disclosingParty, receivingParty)
  }

  function scrollToPricing() {
    pricingRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }

  const displayEmail = email || 'your email'

  return (
    <div className={styles.page}>
      <Nav />

      {/* ── PAGE HEADER ── */}
      <div className={styles.pageHeader}>
        <div className={styles.pageHeaderInner}>
          <p className={styles.eyebrow}>BUSINESS — CONFIDENTIALITY</p>
          <h1 className={styles.headline}>Non-disclosure agreement (NDA)</h1>
          <Stepper />
        </div>
      </div>

      {/* ── TWO-COLUMN LAYOUT ── */}
      <div className={styles.twoColWrap}>
        <div className={styles.twoColInner}>

          {/* LEFT COLUMN */}
          <div className={styles.leftCol}>

            {/* Success banner */}
            <div className={styles.successBanner}>
              <CheckCircleIcon />
              <div className={styles.successText}>
                <p className={styles.successHeading}>Your NDA is ready</p>
                <p className={styles.successSub}>
                  A copy has been sent to <strong>{displayEmail}</strong> and your download is starting now.
                </p>
              </div>
            </div>

            {/* Document delivery card */}
            <div className={styles.deliveryCard}>
              <p className={styles.deliveryLabel}>Your document</p>
              <div className={styles.deliveryRow}>
                <DownloadIcon />
                <div className={styles.deliveryRowBody}>
                  <span className={styles.deliveryRowTitle}>NDA_JaneSmith_AcmeCorp.pdf</span>
                  <span className={styles.deliveryRowSub}>Check your downloads folder</span>
                </div>
                <button className={styles.deliveryAction} onClick={handleDownload}>Download again</button>
              </div>
              <div className={styles.deliveryDivider} />
              <div className={styles.deliveryRow}>
                <EmailIcon />
                <div className={styles.deliveryRowBody}>
                  <span className={styles.deliveryRowTitle}>Sent to {displayEmail}</span>
                  <span className={styles.deliveryRowSub}>PDF and Word versions included</span>
                </div>
                <button className={styles.deliveryAction}>Resend</button>
              </div>
            </div>

            {/* Upgrade card */}
            <div className={styles.upgradeCard}>
              <h3 className={styles.upgradeHeading}>Make sure your NDA actually holds up.</h3>
              <p className={styles.upgradeBody}>
                Your NDA was generated using standard legal language. A LegalShield attorney can review it for your specific situation and make sure it protects you the way you intend.
              </p>
              <ul className={styles.upgradeBullets}>
                {[
                  'Attorney review of your completed NDA',
                  'Unlimited legal questions on any topic',
                  'Access to 900+ provider law firms nationwide',
                  'Create unlimited documents and forms',
                ].map(item => (
                  <li key={item} className={styles.upgradeBulletItem}>
                    <ShieldBulletIcon />
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
              <button className={styles.btnPrimary} onClick={scrollToPricing}>Talk to an attorney</button>
              <button className={styles.btnSecondary}>I&apos;m done for now</button>
            </div>

          </div>

          {/* RIGHT COLUMN */}
          <div className={styles.rightCol}>
            <DocPreview form={form} onDownload={handleDownload} />
          </div>

        </div>
      </div>

      {/* ── PLANS (scroll target) ── */}
      <section className={styles.plansSection} ref={pricingRef}>
        <div className={styles.plansInner}>
          <h2 className={styles.plansSectionHeading}>
            Affordable plans for <em>every</em> need.
          </h2>
          <p className={styles.plansSubtext}>No hourly fees. No surprise bills.</p>
          <div className={styles.plansGrid}>
            <div className={styles.planCard}>
              <div className={styles.planName}>Personal &amp; Family</div>
              <p className={styles.planDesc}>
                Legal advice on a wide range of personal legal issues from lawyers with an average of 21 years of experience.
              </p>
              <div className={styles.planPrice}>$35<span className={styles.planPricePer}>+/mo</span></div>
              <button className={styles.btnPlanFilled}>Shop Plans</button>
            </div>
            <div className={styles.planCard}>
              <div className={styles.planName}>Small Business</div>
              <p className={styles.planDesc}>
                Contracts &amp; Agreements, Business formations, Intellectual Property, and add-on coverage for your business.
              </p>
              <div className={styles.planPrice}>$53.95<span className={styles.planPricePer}>+/mo</span></div>
              <button className={styles.btnPlanFilled}>Shop Plans</button>
            </div>
            <div className={styles.planCard}>
              <div className={styles.planName}>Enterprise</div>
              <p className={styles.planDesc}>
                Legal services and protections designed to give your employees something they truly value — a sense of security.
              </p>
              <div className={styles.planPriceContact}>Contact sales for pricing</div>
              <button className={styles.btnPlanOutlined}>Learn more</button>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  )
}
