import { useState, useEffect, useRef, Fragment } from 'react'
import { useNavigate } from 'react-router-dom'
import Nav from '../../components/Nav/Nav'
import Footer from '../../components/Footer/Footer'
import styles from './FormBuilder.module.css'

// ── Constants ─────────────────────────────────────────────────────────────────

const US_STATES = ['Alabama','Alaska','Arizona','Arkansas','California','Colorado','Connecticut','Delaware','Florida','Georgia','Hawaii','Idaho','Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan','Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire','New Jersey','New Mexico','New York','North Carolina','North Dakota','Ohio','Oklahoma','Oregon','Pennsylvania','Rhode Island','South Carolina','South Dakota','Tennessee','Texas','Utah','Vermont','Virginia','Washington','West Virginia','Wisconsin','Wyoming']
const STEP_LABELS = ['Parties', 'Confidential info', 'Obligations', 'Review']
const RELATIONSHIP_OPTIONS = ['Employer', 'Business owner', 'Freelancer or contractor', 'Individual', 'Other']
const INFO_TYPE_OPTIONS = ['Business plans and strategies', 'Financial information', 'Customer or client lists', 'Trade secrets or proprietary processes', 'Technical or product information', 'Personal or employee information', 'Other']
const DURATION_OPTIONS = ['1 year', '2 years', '3 years', '5 years', 'Indefinitely']
const ALLOWED_USE_OPTIONS = ["Only for performing services you've hired them for", "Only for evaluating a potential business relationship", "Only for the specific project described in this agreement", "For any legitimate business purpose related to our relationship"]
const SHARING_OPTIONS = ["No, they must keep it completely private", "Yes, but only with employees or contractors who need it", "Yes, but only if required by law"]
const INITIAL_FORM = { disclosingParty: '', relationship: '', receivingParty: '', startDate: '', infoTypes: [], description: '', duration: '', allowedUse: '', sharing: '', governingState: '', email: '' }

// ── Helpers ───────────────────────────────────────────────────────────────────

function isValidEmail(v) { return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v.trim()) }

function triggerPDFDownload(disc, recv) {
  const text = `NON-DISCLOSURE AGREEMENT\n\nThis agreement is entered into between ${disc || '[Disclosing party name]'} and ${recv || '[Receiving party name]'}.\n\nThis document was generated by LegalShield. For prototype purposes only.`
  const blob = new Blob([text], { type: 'application/pdf' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = 'NDA_JaneSmith_AcmeCorp.pdf'
  document.body.appendChild(a); a.click(); document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

// ── Stepper ───────────────────────────────────────────────────────────────────

function StepCheckIcon() {
  return <svg width="12" height="12" viewBox="0 0 12 12" fill="none"><polyline points="2,6.5 5,9.5 10,3" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>
}

function Stepper({ step }) {
  return (
    <div className={styles.stepper}>
      {STEP_LABELS.map((label, i) => {
        const n = i + 1
        const done = n < step
        const active = n === step
        return (
          <Fragment key={label}>
            {i > 0 && <div className={`${styles.stepLine} ${n <= step ? styles.stepLineFilled : ''}`} />}
            <div className={styles.stepItem}>
              <div className={`${styles.stepCircle} ${done || active ? styles.stepCircleDark : ''}`}>
                {done ? <StepCheckIcon /> : <span>{n}</span>}
              </div>
              <span className={`${styles.stepLabel} ${active ? styles.stepLabelActive : ''} ${done ? styles.stepLabelDone : ''}`}>{label}</span>
            </div>
          </Fragment>
        )
      })}
    </div>
  )
}

// ── Document Preview ──────────────────────────────────────────────────────────

function Val({ value, placeholder }) {
  return value
    ? <span className={styles.docFilled}>{value}</span>
    : <span className={styles.docPlaceholder}>{placeholder}</span>
}

function DocPreview({ step, form }) {
  const disc = form.disclosingParty
  const recv = form.receivingParty

  const dateDisplay = (() => {
    if (!form.startDate) return null
    const [y, m, d] = form.startDate.split('-').map(Number)
    return new Date(y, m - 1, d).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })
  })()

  const docTitle = (disc || recv)
    ? `Non-disclosure agreement — ${disc || '[Party 1]'} & ${recv || '[Party 2]'}.pdf`
    : 'Document name.pdf'

  return (
    <div className={styles.docPreviewWrap}>
      <div className={styles.docPanel}>
        <div className={styles.docPanelHeader}>
          <span className={styles.docPanelTitle}>{docTitle}</span>
          <span className={styles.previewBadge}>PREVIEW</span>
        </div>
        <div className={styles.docText}>
          <p className={styles.docTextTitle}>Non-Disclosure Agreement</p>
          <hr className={styles.docTextDivider} />

          <p className={styles.docTextParagraph}>
            This Non-Disclosure Agreement (the &ldquo;Agreement&rdquo;) is entered into as of{' '}
            {dateDisplay
              ? <span className={styles.docFilled}>{dateDisplay}</span>
              : <span className={styles.docPlaceholder}>[Date]</span>
            }, by and between:
          </p>

          <p className={styles.docTextParagraph}>
            <Val value={disc} placeholder="[Disclosing Party Name]" />{' '}
            (the &ldquo;Disclosing Party&rdquo;), and{' '}
            <Val value={recv} placeholder="[Receiving Party Name]" />{' '}
            (the &ldquo;Receiving Party&rdquo;). Each party is sometimes referred to herein individually as a &ldquo;Party&rdquo; and collectively as the &ldquo;Parties.&rdquo;
          </p>

          <p className={styles.docTextSectionHead}>Recitals</p>
          <p className={styles.docTextParagraph}>
            WHEREAS, the Disclosing Party possesses certain confidential and proprietary information relating to its business operations, products, services, customers, and strategies; and
          </p>
          <p className={styles.docTextParagraph}>
            WHEREAS, the Receiving Party desires to receive certain of said confidential information for the purpose of evaluating a potential business relationship between the Parties;
          </p>
          <p className={styles.docTextParagraph}>
            NOW, THEREFORE, in consideration of the mutual covenants and agreements contained herein, the Parties agree as follows:
          </p>

          <p className={styles.docTextSectionHead}>1. Confidential Information</p>
          <p className={styles.docTextParagraph}>
            &ldquo;Confidential Information&rdquo; means any and all non-public information disclosed by the Disclosing Party to the Receiving Party, whether disclosed orally, in writing, or by any other means, that is designated as confidential or that reasonably should be understood to be confidential given the nature of the information and the circumstances of disclosure.
          </p>

          <p className={styles.docTextSectionHead}>2. Obligations of Receiving Party</p>
          <p className={styles.docTextParagraph}>
            The Receiving Party agrees to: (a) hold the Confidential Information in strict confidence; (b) not disclose the Confidential Information to any third party without the prior written consent of the Disclosing Party; (c) use the Confidential Information solely for the purposes described in this Agreement; and (d) protect the Confidential Information using the same degree of care it uses to protect its own confidential information, but in no event less than reasonable care.
          </p>

          <p className={styles.docTextSectionHead}>3. Term</p>
          <p className={styles.docTextParagraph}>
            The obligations of confidentiality set forth in this Agreement shall commence on the date first written above and shall continue for a period of{' '}
            {form.duration
              ? <span className={styles.docFilled}>{form.duration.toLowerCase()}</span>
              : <span className={styles.docPlaceholder}>[Duration]</span>
            }{' '}
            thereafter, unless earlier terminated by written agreement of the Parties.
          </p>

          <p className={styles.docTextSectionHead}>4. Governing Law</p>
          <p className={styles.docTextParagraph}>
            This Agreement shall be governed by and construed in accordance with the laws of the State of{' '}
            {form.governingState
              ? <span className={styles.docFilled}>{form.governingState}</span>
              : <span className={styles.docPlaceholder}>[State]</span>
            }, without regard to its conflict of law provisions.
          </p>

          <hr className={styles.docTextDivider} />
          <p className={styles.docTextSectionHead}>Signatures</p>
          <div className={styles.docTextSigBlock}>
            <div className={styles.docTextSigCol}>
              <div className={styles.docTextSigLine}>
                <Val value={disc} placeholder="[Disclosing Party]" />
              </div>
              <div className={styles.docTextSigLine}>Signature</div>
              <div className={styles.docTextSigLine}>Date</div>
            </div>
            <div className={styles.docTextSigCol}>
              <div className={styles.docTextSigLine}>
                <Val value={recv} placeholder="[Receiving Party]" />
              </div>
              <div className={styles.docTextSigLine}>Signature</div>
              <div className={styles.docTextSigLine}>Date</div>
            </div>
          </div>

          <div className={styles.watermark}>PREVIEW</div>
        </div>
      </div>
      <p className={styles.docPageLabel}>Preview: page 1 of 4</p>
    </div>
  )
}

// ── Field primitives ──────────────────────────────────────────────────────────

function FieldWrap({ label, helper, children }) {
  return (
    <div className={styles.fieldWrap}>
      {label && <label className={styles.fieldLabel}>{label}</label>}
      {children}
      {helper && <p className={styles.fieldHelper}>{helper}</p>}
    </div>
  )
}

function TextInput({ label, placeholder, helper, value, onChange }) {
  return (
    <FieldWrap label={label} helper={helper}>
      <input
        type="text"
        className={`${styles.input} ${value ? styles.inputFilled : ''}`}
        placeholder={placeholder}
        value={value}
        onChange={e => onChange(e.target.value)}
      />
    </FieldWrap>
  )
}

function SelectInput({ label, placeholder, helper, value, onChange, options }) {
  return (
    <FieldWrap label={label} helper={helper}>
      <select
        className={`${styles.input} ${styles.select} ${value ? styles.inputFilled : ''}`}
        value={value}
        onChange={e => onChange(e.target.value)}
      >
        <option value="">{placeholder || 'Select…'}</option>
        {options.map(o => <option key={o} value={o}>{o}</option>)}
      </select>
    </FieldWrap>
  )
}

function TextareaInput({ label, placeholder, helper, value, onChange }) {
  return (
    <FieldWrap label={label} helper={helper}>
      <textarea
        className={`${styles.input} ${styles.textarea} ${value ? styles.inputFilled : ''}`}
        placeholder={placeholder}
        value={value}
        onChange={e => onChange(e.target.value)}
        rows={4}
      />
    </FieldWrap>
  )
}

function CheckboxGroup({ label, helper, options, selected, onChange }) {
  function toggle(opt) {
    onChange(selected.includes(opt) ? selected.filter(v => v !== opt) : [...selected, opt])
  }
  return (
    <FieldWrap label={label} helper={helper}>
      <div className={styles.checkGroup}>
        {options.map(opt => (
          <label key={opt} className={styles.checkRow}>
            <input
              type="checkbox"
              className={styles.checkInput}
              checked={selected.includes(opt)}
              onChange={() => toggle(opt)}
            />
            <span>{opt}</span>
          </label>
        ))}
      </div>
    </FieldWrap>
  )
}

function RadioGroup({ label, helper, options, value, onChange }) {
  return (
    <FieldWrap label={label} helper={helper}>
      <div className={styles.radioGroup}>
        {options.map(opt => (
          <label key={opt} className={styles.radioRow}>
            <input
              type="radio"
              className={styles.radioInput}
              checked={value === opt}
              onChange={() => onChange(opt)}
            />
            <span>{opt}</span>
          </label>
        ))}
      </div>
    </FieldWrap>
  )
}

// ── Step 1: Parties ───────────────────────────────────────────────────────────

function Step1({ form, update, onBack, onNext }) {
  return (
    <div className={styles.stepContent}>
      <h2 className={styles.stepHeading}>Who is this NDA between?</h2>
      <p className={styles.stepSub}>Tell us about the two parties involved. This information will appear at the top of your agreement.</p>

      <div className={styles.fieldGroup}>
        <p className={styles.sectionLabel}>Disclosing party</p>
        <TextInput
          label="Your full name or business name"
          placeholder="e.g. Jane Smith or Acme Corp LLC"
          helper="This is the party sharing confidential information. Enter your legal name or registered business name."
          value={form.disclosingParty}
          onChange={v => update('disclosingParty', v)}
        />
        <SelectInput
          label="Your relationship to the other party"
          value={form.relationship}
          onChange={v => update('relationship', v)}
          options={RELATIONSHIP_OPTIONS}
        />
        <p className={styles.sectionLabel}>Receiving party</p>
        <TextInput
          label="Recipient's full name or business name"
          placeholder="e.g. John Doe or Bright Ideas Inc."
          helper="This is the party receiving and agreeing to protect your confidential information."
          value={form.receivingParty}
          onChange={v => update('receivingParty', v)}
        />
        <FieldWrap label="Agreement start date">
          <input
            type="date"
            className={`${styles.input} ${form.startDate ? styles.inputFilled : ''}`}
            value={form.startDate}
            onChange={e => update('startDate', e.target.value)}
          />
        </FieldWrap>
      </div>

      <div className={styles.stepCtas}>
        <button className={styles.btnBack} onClick={onBack}>← Back</button>
        <button className={styles.btnNext} onClick={onNext}>Save and continue →</button>
      </div>
    </div>
  )
}

// ── Step 2: Confidential Info ─────────────────────────────────────────────────

function Step2({ form, update, onBack, onNext }) {
  return (
    <div className={styles.stepContent}>
      <h2 className={styles.stepHeading}>What information needs to stay confidential?</h2>
      <p className={styles.stepSub}>Describe the confidential information you're sharing. The more specific you are, the stronger your protection.</p>

      <div className={styles.fieldGroup}>
        <CheckboxGroup
          label="What kind of information are you protecting?"
          options={INFO_TYPE_OPTIONS}
          selected={form.infoTypes}
          onChange={v => update('infoTypes', v)}
        />
        <TextareaInput
          label="Describe the confidential information in your own words"
          placeholder="e.g. Details about our new product launch including pricing strategy and supplier relationships."
          helper="A brief description helps make the agreement specific to your situation."
          value={form.description}
          onChange={v => update('description', v)}
        />
        <SelectInput
          label="How long should this information stay confidential?"
          value={form.duration}
          onChange={v => update('duration', v)}
          options={DURATION_OPTIONS}
        />
      </div>

      <div className={styles.stepCtas}>
        <button className={styles.btnBack} onClick={onBack}>← Back</button>
        <button className={styles.btnNext} onClick={onNext}>Save and continue →</button>
      </div>
    </div>
  )
}

// ── Step 3: Obligations ───────────────────────────────────────────────────────

function Step3({ form, update, onBack, onNext }) {
  return (
    <div className={styles.stepContent}>
      <h2 className={styles.stepHeading}>What can the recipient do with your information?</h2>
      <p className={styles.stepSub}>These are the rules the receiving party must follow. We've set sensible defaults — review and adjust if needed.</p>

      <div className={styles.fieldGroup}>
        <RadioGroup
          label="What is the recipient allowed to use this information for?"
          helper="Limit their use to a specific purpose for the strongest protection."
          options={ALLOWED_USE_OPTIONS}
          value={form.allowedUse}
          onChange={v => update('allowedUse', v)}
        />
        <RadioGroup
          label="Can the recipient share your information with anyone?"
          helper="In most cases you'll want to restrict sharing."
          options={SHARING_OPTIONS}
          value={form.sharing}
          onChange={v => update('sharing', v)}
        />
        <SelectInput
          label="Which state's laws govern this agreement?"
          placeholder="Select a state"
          value={form.governingState}
          onChange={v => update('governingState', v)}
          options={US_STATES}
        />
      </div>

      <div className={styles.stepCtas}>
        <button className={styles.btnBack} onClick={onBack}>← Back</button>
        <button className={styles.btnNext} onClick={onNext}>Save and continue →</button>
      </div>
    </div>
  )
}

// ── Step 4: Review & Email Gate ───────────────────────────────────────────────

function Step4({ form, update, onBack, onEditStep, onSubmit }) {
  const [emailError, setEmailError] = useState('')

  const rows = [
    { label: 'Disclosing party', value: form.disclosingParty, editStep: 1 },
    { label: 'Receiving party',  value: form.receivingParty,  editStep: 1 },
    { label: 'Relationship',     value: form.relationship,    editStep: 1 },
    { label: 'Effective date',   value: form.startDate,       editStep: 1 },
    { label: "What's protected", value: form.infoTypes.length ? form.infoTypes.join(', ') : form.description, editStep: 2 },
    { label: 'Duration',         value: form.duration,        editStep: 2 },
    { label: 'Jurisdiction',     value: form.governingState,  editStep: 3 },
  ]

  function handleSubmit() {
    if (!isValidEmail(form.email)) {
      setEmailError('Please enter a valid email address')
      return
    }
    setEmailError('')
    onSubmit()
  }

  return (
    <div className={styles.stepContent}>
      <h2 className={styles.stepHeading}>Your NDA is ready to download.</h2>
      <p className={styles.stepSub}>Take a moment to review your details below. Everything look right? Enter your email to get your completed NDA.</p>

      {/* Summary card */}
      <div className={styles.reviewCard}>
        <p className={styles.reviewCardLabel}>Review your details</p>
        <div className={styles.reviewTable}>
          {rows.map(row => (
            <div className={styles.reviewRow} key={row.label}>
              <span className={styles.reviewFieldLabel}>{row.label}</span>
              <span className={styles.reviewValue}>{row.value || <span className={styles.reviewEmpty}>—</span>}</span>
              <button className={styles.editBtn} onClick={() => onEditStep(row.editStep)}>Edit</button>
            </div>
          ))}
        </div>
      </div>

      {/* Email gate */}
      <div className={styles.emailCard}>
        <h3 className={styles.emailCardHeading}>Your NDA is ready.</h3>
        <p className={styles.emailCardSub}>Enter your email and we'll send you a copy and unlock your download.</p>
        <div className={`${styles.emailInputRow} ${emailError ? styles.emailInputRowError : ''}`}>
          <input
            type="email"
            className={styles.emailInput}
            placeholder="Email address"
            value={form.email}
            onChange={e => { update('email', e.target.value); if (emailError) setEmailError('') }}
            onKeyDown={e => e.key === 'Enter' && handleSubmit()}
          />
          <button className={styles.emailSubmitBtn} onClick={handleSubmit} aria-label="Submit">→</button>
        </div>
        {emailError && <p className={styles.emailError}>{emailError}</p>}
        <p className={styles.emailDisclaimer}>
          By continuing you agree to receive emails from LegalShield. View our Privacy Policy. Legal language is provided by LegalShield attorneys and may not be edited without a paid plan.
        </p>
      </div>

      <div className={styles.stepCtas}>
        <button className={styles.btnBack} onClick={onBack}>← Back</button>
      </div>
    </div>
  )
}

// ── Main Component ────────────────────────────────────────────────────────────

export default function FormBuilder() {
  const navigate = useNavigate()
  const [step, setStep] = useState(1)
  const [form, setForm] = useState(INITIAL_FORM)
  const topRef = useRef(null)

  useEffect(() => {
    topRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }, [step])

  function update(field, value) {
    setForm(prev => ({ ...prev, [field]: value }))
  }

  function goBack() {
    if (step === 1) navigate('/forms/nda')
    else setStep(s => s - 1)
  }

  function goNext() {
    setStep(s => s + 1)
  }

  function editStep(n) {
    setStep(n)
  }

  function handleSubmit() {
    triggerPDFDownload(form.disclosingParty, form.receivingParty)
    navigate('/forms/nda/confirmation', { state: { email: form.email, disclosingParty: form.disclosingParty, receivingParty: form.receivingParty } })
  }

  return (
    <div className={styles.page}>
      <Nav />

      {/* Page header — full width */}
      <div className={styles.pageHeader} ref={topRef}>
        <div className={styles.pageHeaderInner}>
          <p className={styles.eyebrow}>BUSINESS — CONFIDENTIALITY</p>
          <h1 className={styles.headline}>Non-disclosure agreement (NDA)</h1>
          <Stepper step={step} />
        </div>
      </div>

      {/* Two-column layout */}
      <div className={styles.twoColWrap}>
        <div className={styles.twoColInner}>
          <div className={styles.leftCol}>
            {step === 1 && <Step1 form={form} update={update} onBack={goBack} onNext={goNext} />}
            {step === 2 && <Step2 form={form} update={update} onBack={goBack} onNext={goNext} />}
            {step === 3 && <Step3 form={form} update={update} onBack={goBack} onNext={goNext} />}
            {step === 4 && <Step4 form={form} update={update} onBack={goBack} onEditStep={editStep} onSubmit={handleSubmit} />}
          </div>
          <div className={styles.rightCol}>
            <DocPreview step={step} form={form} />
          </div>
        </div>
      </div>

      <Footer />
    </div>
  )
}
